
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package grammar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPAREN = 6;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int error = 1;
  public static final int LPAREN = 5;
  public static final int OR = 3;
  public static final int EOF = 0;
  public static final int VARIABLE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "VARIABLE"
  };
}

